### ISSUE TITLE
Please add more group members as collaborators

### ISSUE THREAD

**Issue by aviaryan** [aviaryan/shape-recog#3]
@saurabhjn76 @RajuKoushik @mayankpi @KamalAwasthi 
I don't remember who where the other 5 group members. Please add them as a collaborator to this repo.

**Comment by saurabhjn76** [comment]
Here is the list of our other 5 group members.
@Sahil26, @vishal3011,karan,Rajat,Chirag.

**Comment by saurabhjn76** [comment]
Only owner can add more collaborators.

**Comment by aviaryan** [comment]
Rajat is @raj-at
